name: 'validate TF'
description: 'run all pre-req steps and the actual TF code validation'
inputs:
  tf_version:  # id of input
    description: 'TF version used to validate code.'
    required: true
  path:
    description: 'Path to code that will be validated.'
    required: true
runs:
  using: "composite"
  steps:
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf_version }}
    - name: run validation for ${{ inputs.path }}
      run: |
        cd "$GITHUB_WORKSPACE"/${{ inputs.path }}
        pwd
        terraform init -backend=false
        terraform validate
      shell: bash
