formatter: "markdown document" # this is required
version: ""
header-from: ".header.md"

output:
  file: README.md
  mode: replace

sort:
  enabled: false

settings:
  indent: 3
  lockfile: false

content: |-
  {{ .Header }}

  ## Module's Required Inputs

  Name | Type | Description
  --- | --- | ---
  {{- range .Module.Inputs }}
  {{- if .Required }}
  [`{{ .Name }}`](#{{ .Name }}) | `{{ (split "(" .Type.Raw)._0 }}` | {{ (split "." .Description.Raw)._0 }}.
  {{- end -}}
  {{ end }}

  {{- $optional := false }}
  {{- range .Module.Inputs }}{{ if not .Required }}{{ $optional = true }}{{ end }}{{ end }}

  {{ if $optional }}
  ## Module's Optional Inputs

  Name | Type | Description
  --- | --- | ---
  {{- range .Module.Inputs }}
  {{- if not .Required }}
  [`{{ .Name }}`](#{{ .Name }}) | `{{ (split "(" .Type.Raw)._0 }}` | {{ (split "." .Description.Raw)._0 }}.
  {{- end -}}
  {{ end }}
  {{ end }}

  {{ if ne (len .Module.Outputs) 0 }}
  ## Module's Outputs

  Name |  Description
  --- | ---
  {{- range .Module.Outputs }}
  `{{ .Name }}` | {{ .Description.Raw }}
  {{- end }}
  {{- end }}

  ## Module's Nameplate

  {{ if ne (len .Module.Requirements) 0 }}
  Requirements needed by this module:
  {{ range .Module.Requirements }}
  - `{{ .Name }}`{{ if .Version }}, version: {{ .Version }}{{ end }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.Providers) 0 }}
  Providers used in this module:
  {{ range .Module.Providers }}
  - `{{ .Name }}`{{ if .Version }}, version: {{ .Version }}{{ end }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.ModuleCalls) 0 }}
  Modules used in this module:
  Name | Version | Source | Description
  --- | --- | --- | ---
  {{- range .Module.ModuleCalls }}
  `{{ .Name }}` | {{ if .Version }}{{ .Version }}{{ else }}-{{ end }} | {{ .Source }} | {{ .Description }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.Resources) 0 }}
  Resources used in this module:
  {{ range .Module.Resources }}
  - `{{ .Type }}` ({{ .Mode }})
  {{- end }}
  {{- end }}

  ## Inputs/Outpus details

  ### Required Inputs

  {{ range .Module.Inputs }}
  {{ if .Required -}}
  #### {{ .Name }}
  
  {{ .Description }}
  
  Type: {{ if lt (len (split "\n" .Type.Raw)) 2 }}{{ .Type }}{{ else }}

  ```hcl
  {{ .Type }}
  ```
  {{ end }}
  
  <sup>[back to list](#modules-required-inputs)</sup>
  {{ end }}
  {{- end }}

  {{ if $optional }}
  ### Optional Inputs

  {{ range .Module.Inputs }}
  {{ if not .Required -}}
  #### {{ .Name }}

  {{ .Description }}

  Type: {{ if lt (len (split "\n" .Type.Raw)) 2 }}{{ .Type }}{{ else }}

  ```hcl
  {{ .Type }}
  ```
  {{ end }}

  Default value: `{{ .Default }}`

  <sup>[back to list](#modules-optional-inputs)</sup>
  {{ end }}
  {{- end }}
  {{ end }}
