name: 'Terratest'
description: 'Runs Terratest for a specified path.'
inputs:
  tf_version:
    description: 'TF version used.'
    required: true
  path:
    description: 'Path to Terraform module.'
    required: true
  terratest_action:
    description: The action (name of a test in Terratest) that will be passed to the Makefile's ACTION parameter
    type: string
    required: true
  pr-id:
    description: A PR number. Optional value, you might want to use it to prefix resources created for a particular PR to identify them easly.
    type: string
    default: ""
    required: false

runs:
  using: "composite"
  steps:

    - name: setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf_version }}
        terraform_wrapper: false

    - name: setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    - name: ${{ inputs.terratest_action }} infrastructure
      env:
        TPATH: ${{ inputs.path }}
        ARM_USE_OIDC: true
        ARM_SKIP_PROVIDER_REGISTRATION: true
        ACTION: ${{ inputs.terratest_action }}
        PRID: ${{ inputs.pr-id }}
      shell: bash
      run: make $TPATH ACTION=$ACTION
