name: 'TF plan/apply'
description: 'Runs Terraform plan and/or apply for a specified path.'
inputs:
  tf_version:
    description: 'TF version used.'
    required: true
  path:
    description: 'Path to Terraform module.'
    required: true
  do_apply:
    description: When set to true runs also apply
    type: boolean
    default: false
  indepotency:
    description: When set to true runs plan to on already applied configuration
    type: boolean
    default: true
runs:
  using: "composite"
  steps:
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf_version }}

    - name: set UUID value
      id: uuid
      shell: bash
      run: echo "::set-output name=uuid::$(uuidgen | tr '[:upper:]' '[:lower:]')"

    - name: login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    - name: run plan
      id: plan
      if: ${{ ! inputs.do_apply }}
      env:
        TPATH: ${{ inputs.path }}
        ARM_USE_OIDC: true
        UUID: ${{ steps.uuid.outputs.uuid }}
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE/$TPATH"
        make plan

    - name: run apply
      if: inputs.do_apply
      env:
        TPATH: ${{ inputs.path }}
        ARM_USE_OIDC: true
        UUID: ${{ steps.uuid.outputs.uuid }}
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE/$TPATH"
        make apply

    - name: test indepotency
      if: inputs.do_apply && inputs.indepotency
      env:
        TPATH: ${{ inputs.path }}
        ARM_USE_OIDC: true
        UUID: ${{ steps.uuid.outputs.uuid }}
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE/$TPATH"
        make indepotency

    - name: run destroy
      if: inputs.do_apply && always()
      env:
        TPATH: ${{ inputs.path }}
        ARM_USE_OIDC: true
        UUID: ${{ steps.uuid.outputs.uuid }}
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE/$TPATH"
        make destroy
