name: PR CI
run-name: "CI pipeline for PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

permissions:
  contents: read
  actions: read
  id-token: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: ['main']

jobs:
  release_wrkflw:
    name: Do release
    uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/release_ci.yml@makefile-with-terratest
    secrets: inherit
    with:
      cloud: azure
      max_parallel: 5
      terratest_action: Idempotence # keep in mind that this has to start with capital letter

  # pr_ci_wrkflw:
  #   name: Run CI
  #   uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/pr_ci.yml@makefile-with-terratest
  #   secrets: inherit
  #   if: github.actor != 'dependabot[bot]'
  #   with:
  #     cloud: azure
  #     tf_version: 1.2 1.3 1.4 1.5
  #     max_parallel: 20
  #     terratest_action: Plan # keep in mind that this has to start with capital letter


