name: Release CI
run-name: "Continous Release"


permissions:
  contents: write
  issues: read
  id-token: write

on:
  workflow_dispatch:
  # push:
  #   branches: main

concurrency: release

jobs:
  release_wrkflw:
    name: Do release
    uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/release_ci.yml@makefile-with-terratest
    secrets: inherit
    with:
      cloud: azure
      validate_max_parallel: 20
      test_max_parallel: 5
      terratest_action: Idempotence # keep in mind that this has to start with capital letter