name: PR CI
run-name: "CI pipeline for PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

permissions:
  contents: read
  actions: read
  id-token: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: ['main']

jobs:
  pr_ci_wrkflw:
    name: Run CI
    uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/pr_ci.yml@v1.2.0
    secrets: inherit
    if: github.actor != 'dependabot[bot]'
    with:
      cloud: azure
      do_apply: true
      # tf_version: 1.2 1.3 1.4 1.5

