name: Release CI
run-name: "Continous Release"


permissions:
  contents: write
  issues: read
  id-token: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 4' # this means every Thursday @1am UTC

jobs:
  release_wrkflw:
    name: Do release
    uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/release_ci.yml@v2
    secrets: inherit
    with:
      cloud: azure
      max_parallel: 10
      do_apply: true
