---
name: TF Validate
# description: Validate examples and modules against variety of TF versions

on:
  workflow_dispatch:

env:
  # tf_versions needs to be a string of TF versions we would like to test against
  # versions have to be space delimited
  # when providing only major.minor version the latest patch level will be used
  tf_versions: 1.0 1.1 1.2 1.3

jobs: 
  prerequisites:
    name: gather prerequisites
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.preqs.outputs.modules }}
      examples: ${{ steps.preqs.outputs.examples }}
      tf_versions: ${{ steps.preqs.outputs.tf_versions }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set outputs
        id: preqs
        run: |
          echo "::set-output name=modules::$(find modules -maxdepth 1 -mindepth 1 -type d -not \( -name ".?*" \) | jq -R -s -c 'split("\n")[:-1]')"
          echo "::set-output name=examples::$(find examples -maxdepth 1 -mindepth 1 -type d -not \( -name ".?*" \) | jq -R -s -c 'split("\n")[:-1]')"
          echo "::set-output name=tf_versions::$(echo ${tf_versions}| tr " " "\n" | jq -R -s -c 'split("\n")[:-1]')"

  modules:
    needs: [prerequisites]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_versions: ${{ fromJson(needs.prerequisites.outputs.tf_versions) }}
        modules: ${{ fromJson(needs.prerequisites.outputs.modules) }}
    name: '${{ matrix.modules }}@${{ matrix.tf_versions }}'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run validation
        uses: ./.github/actions/validate_tf
        with:
          path: ${{ matrix.modules }}
          tf_version: ${{ matrix.tf_versions }}
  examples:
    needs: [prerequisites]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_versions: ${{ fromJson(needs.prerequisites.outputs.tf_versions) }}
        examples: ${{ fromJson(needs.prerequisites.outputs.examples) }}
    name: '${{ matrix.examples }}@${{ matrix.tf_versions }}'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run validation
        uses: ./.github/actions/validate_tf
        with:
          path: ${{ matrix.examples }}
          tf_version: ${{ matrix.tf_versions }}
