name: ChatOPS Validate
run-name: "On demand Validate test for PR - (#${{ github.event.inputs.pr-id }}) ${{ github.event.inputs.pr-title }}"

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      paths:
        description: Space delimited list of module paths to test
        type: string
        required: true
      tf_version:
        description: Terraform versions to use for tests, comma-separated list
        type: string
      pr-id:
        description: ID of the PR that triggered this workflow
        type: string
        required: true
      pr-title: 
        description: Title of the PR that triggered this workflow
        type: string
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        type: string
        required: true
      branch:
        description: Branch on which the tests should run
        type: string
        default: main

jobs:
  test:
    name: Run validate test
    concurrency:
      group: chatops-validate-${{ github.event.issue.number }}
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/test_command.yml@v2.1.2
    secrets: inherit
    with:
      paths: ${{ inputs.paths }}
      tf_version: ${{ inputs.tf_version }}
      pr-id: ${{ inputs.pr-id }}
      comment-id: ${{ inputs.comment-id }}
      branch: ${{ inputs.branch }}
      terratest_action: Validate
